let MATERIALS=[];let TOOLS=[];
const state={rows:Array.from({length:50},()=>({qty:"",material:"",tool:""})),laborHours:0,laborRate:75};
const $=id=>document.getElementById(id);const money=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(n)||0);
const materialByName=name=>MATERIALS.find(m=>m.name===name);const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
async function loadDatabase(){try{const response=await fetch("./database.json",{cache:"no-store"});if(!response.ok)throw new Error("HTTP "+response.status);const database=await response.json();if(!Array.isArray(database.materials)||!Array.isArray(database.tools))throw new Error("Invalid database");MATERIALS=database.materials;TOOLS=database.tools;renderRows();renderTools();renderPrices()}catch(error){console.error("Database loading error:",error);const body=$("materialBody");if(body)body.innerHTML='<tr><td colspan="5" class="db-error">Database could not be loaded.</td></tr>'}}
function materialOptions(selected=""){const groups={};MATERIALS.forEach(m=>(groups[m.category]??=[]).push(m));let html='<option value=""></option>';for(const category of Object.keys(groups)){html+='<optgroup label="'+esc(category)+'">';groups[category].forEach(m=>{html+='<option value="'+esc(m.name)+'"'+(m.name===selected?" selected":"")+'>'+esc(m.name)+"</option>"});html+="</optgroup>"}return html}
function toolOptions(selected=""){let html='<option value=""></option>';TOOLS.forEach(t=>html+='<option value="'+esc(t)+'"'+(t===selected?" selected":"")+'>'+esc(t)+"</option>");return html}
function renderRows(){const body=$("materialBody");if(!body)return;body.innerHTML=state.rows.map((row,index)=>{const material=materialByName(row.material);const price=material?.price||0;return '<tr><td><input type="number" min="0" step="1" value="'+esc(row.qty)+'" data-i="'+index+'" class="qty-input"></td><td><select data-i="'+index+'" class="material-input">'+materialOptions(row.material)+'</select></td><td class="cost-each">'+money(price)+'</td><td class="cost-total">'+money((Number(row.qty)||0)*price)+'</td><td><select data-i="'+index+'" class="tool-input">'+toolOptions(row.tool)+'</select></td></tr>'}).join("");updateTotals()}
function updateTotals(){let materialTotal=0;state.rows.forEach((row,index)=>{const price=materialByName(row.material)?.price||0;const total=(Number(row.qty)||0)*price;materialTotal+=total;const tr=$("materialBody")?.rows[index];if(tr){tr.querySelector(".cost-each").textContent=money(price);tr.querySelector(".cost-total").textContent=money(total)}});const tax=materialTotal*.0625;const labor=(Number(state.laborHours)||0)*(Number(state.laborRate)||0);if($("materialTotal"))$("materialTotal").textContent=money(materialTotal);if($("taxTotal"))$("taxTotal").textContent=money(tax);if($("materialsWithTax"))$("materialsWithTax").textContent=money(materialTotal+tax);if($("laborTotal"))$("laborTotal").textContent=money(labor);if($("grandTotal"))$("grandTotal").textContent=money(materialTotal+tax+labor)}
function setupMaterialEvents(){const body=$("materialBody");if(!body)return;body.addEventListener("input",e=>{const i=Number(e.target.dataset.i);if(Number.isNaN(i))return;if(e.target.classList.contains("qty-input"))state.rows[i].qty=e.target.value;updateTotals()});body.addEventListener("change",e=>{const i=Number(e.target.dataset.i);if(Number.isNaN(i))return;if(e.target.classList.contains("material-input"))state.rows[i].material=e.target.value;if(e.target.classList.contains("tool-input"))state.rows[i].tool=e.target.value;updateTotals()})}
function setupLaborEvents(){$("laborHours")?.addEventListener("input",e=>{state.laborHours=e.target.value;updateTotals()});$("laborRate")?.addEventListener("input",e=>{state.laborRate=e.target.value;updateTotals()})}
function renderTools(){const grid=$("toolListGrid");if(!grid)return;grid.innerHTML=TOOLS.map(t=>'<div class="tool-item"><span>'+esc(t)+'</span><select><option>Status</option><option>Have</option><option>Need</option></select><input type="number" min="1" value="1"></div>').join("")}
function renderPrices(search=""){const body=$("priceBody");if(!body)return;const q=search.toLowerCase().trim();body.innerHTML=MATERIALS.filter(m=>((m.category||"")+" "+(m.name||"")+" "+(m.unit||"")+" "+(m.notes||"")).toLowerCase().includes(q)).map(m=>'<tr><td>'+esc(m.category)+'</td><td>'+esc(m.name)+'</td><td>'+esc(m.unit)+'</td><td>'+money(m.price)+'</td><td>'+esc(m.notes)+'</td></tr>').join("")}
function setupNavigation(){document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav-btn").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".page-section").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.section)?.classList.add("active")})}
function setupClearButton(){$("clearBtn")?.addEventListener("click",()=>{if(!confirm("Clear this project?"))return;state.rows=Array.from({length:50},()=>({qty:"",material:"",tool:""}));state.laborHours=0;state.laborRate=75;if($("jobName"))$("jobName").value="";if($("projectType"))$("projectType").value="";if($("laborHours"))$("laborHours").value=0;if($("laborRate"))$("laborRate").value=75;renderRows()})}
function init(){if($("jobDate"))$("jobDate").valueAsDate=new Date();setupMaterialEvents();setupLaborEvents();setupNavigation();setupClearButton();$("printBtn")?.addEventListener("click",()=>window.print());$("priceSearch")?.addEventListener("input",e=>renderPrices(e.target.value));loadDatabase()}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init):init();